# Generated by Django 5.0.14 on 2026-09-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forumpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='forum/%Y/%m/', verbose_name='Ảnh đại diện'),
        ),
    ]
