# Generated by Django 5.0.14 on 2026-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_seed_more_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
