# Generated by Django 5.0.14 on 2026-09-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lớp'),
        ),
    ]
