# Generated by Django 5.0.14 on 2026-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_moderationlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('warn', 'Cảnh báo'), ('hide', 'Ẩn nội dung'), ('delete', 'Xóa nội dung'), ('restore', 'Khôi phục nội dung'), ('approve_content', 'Duyệt nội dung chờ kiểm duyệt'), ('reject_content', 'Từ chối nội dung chờ kiểm duyệt'), ('lock_account', 'Khóa tài khoản'), ('unlock_account', 'Mở khóa tài khoản'), ('role_change', 'Thay đổi vai trò'), ('approve_group', 'Duyệt yêu cầu tạo nhóm'), ('reject_group', 'Từ chối yêu cầu tạo nhóm'), ('disable_group', 'Vô hiệu hóa nhóm'), ('enable_group', 'Kích hoạt lại nhóm'), ('appeal_accepted', 'Chấp nhận kháng nghị'), ('appeal_rejected', 'Từ chối kháng nghị')], max_length=30),
        ),
    ]
