# Generated by Django 5.0.14 on 2026-09-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian diễn ra sự kiện'),
        ),
    ]
