# Generated by Django 5.0.14 on 2026-09-27 10:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_seed_demo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
