# Generated by Django 5.0.14 on 2026-09-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_seed_announcement_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/featured/%Y/%m/', verbose_name='Ảnh đại diện'),
        ),
    ]
