# Generated by Django 5.0.14 on 2026-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcement_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
