# Generated by Django 5.0.14 on 2026-09-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_grouppost_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/covers/', verbose_name='Ảnh bìa nhóm'),
        ),
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='groups/logos/', verbose_name='Logo nhóm'),
        ),
    ]
