# Generated by Django 5.0.14 on 2026-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_cover_image_group_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('active', 'Đang hoạt động'), ('rejected', 'Bị từ chối'), ('disabled', 'Đã vô hiệu hóa')], default='pending', max_length=20),
        ),
    ]
