# Generated by Django 5.0.14 on 2026-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
