# Generated by Django 5.0.14 on 2026-09-21 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('comment', 'Có bình luận mới'), ('like', 'Có lượt thích mới'), ('new_announcement', 'Thông báo mới'), ('group_approved', 'Yêu cầu tạo nhóm được duyệt'), ('group_rejected', 'Yêu cầu tạo nhóm bị từ chối'), ('moderation', 'Cập nhật kiểm duyệt'), ('appeal_result', 'Kết quả kháng nghị')], max_length=30)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_comment', models.BooleanField(default=True)),
                ('notify_on_like', models.BooleanField(default=True)),
                ('notify_on_announcement', models.BooleanField(default=True)),
                ('notify_on_group_activity', models.BooleanField(default=True)),
                ('notify_on_moderation', models.BooleanField(default=True)),
                ('email_digest', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
