# Generated by Django 5.0.14 on 2026-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('comment', 'Có bình luận mới'), ('like', 'Có lượt thích mới'), ('new_announcement', 'Thông báo mới'), ('group_approved', 'Yêu cầu tạo nhóm được duyệt'), ('group_rejected', 'Yêu cầu tạo nhóm bị từ chối'), ('group_invitation', 'Lời mời tham gia nhóm'), ('group_join_request', 'Có yêu cầu xin tham gia nhóm'), ('group_join_approved', 'Yêu cầu tham gia nhóm được duyệt'), ('group_join_rejected', 'Yêu cầu tham gia nhóm bị từ chối'), ('moderation', 'Cập nhật kiểm duyệt'), ('appeal_result', 'Kết quả kháng nghị'), ('mention', 'Được gắn thẻ')], max_length=30),
        ),
    ]
